### ISSUE TITLE
This doesn't work!

### ISSUE THREAD

**Issue by whamsicore** [threenine/gridsome-plugin-gtag#2]
{
  "name": "my-project",
  "private": true,
  "scripts": {
    "build": "gridsome build",
    "develop": "gridsome develop",
    "explore": "gridsome explore"
  },
  "dependencies": {
    "@gridsome/remark-prismjs": "0.5.0",
    "@gridsome/source-filesystem": "^0.6.2",
    "@gridsome/transformer-remark": "^0.6.4",
    "gridsome": "^0.7.23",
    "gridsome-plugin-gtag": "^0.1.10"
  }
}

This package just plain doesn't work...

**Comment by garywoodfine** [comment]
have you configured it correctly in the Gridsome Config?

**Comment by whamsicore** [comment]
Problem solved. 1) I created the .env file and put in the analytics config. 2) I placed actual analytics events in the component files, such as under the mounted event.
